PATCH /api/2.4/tenders/032ad48817a74526a52bbdc065449884/qualifications/525fe80947ff4a25b772d2bea5e0ca83?acc_token=b0f3fe41a6644097a0f0c1eebb4442ae HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "lotID": "0e0d16f25ed5424a9dc07eeee9976392", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "5e7484de25494044b2f974592af01d5f", 
    "date": "2017-10-06T17:05:17.262396+03:00", 
    "id": "525fe80947ff4a25b772d2bea5e0ca83"
  }
}

